# Generated by Django 6.0.6 on 2026-06-15 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponto_de_partida', models.CharField(max_length=100)),
                ('ponto_de_chegada', models.CharField(max_length=100)),
                ('dias_da_semana', models.CharField(max_length=50)),
                ('horario_saida', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_de_usuario', models.CharField(choices=[('cliente', 'Passageiro'), ('guiche', 'Guichê / Operador'), ('administrador', 'Administrador')], default='cliente', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_parada', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(help_text='Ordem da parada no trajeto')),
                ('horario_estimado', models.TimeField()),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='Usuario.rotas')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_partida', models.DateField()),
                ('horario_saida', models.TimeField()),
                ('capacidade_maxima', models.PositiveIntegerField()),
                ('administrador', models.ForeignKey(limit_choices_to={'tipo_de_usuario': 'administrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Usuario.usuario')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagens', to='Usuario.rotas')),
            ],
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bilhete', models.CharField(max_length=20, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('ponto_embarque', models.CharField(max_length=100)),
                ('ponto_desembarque', models.CharField(max_length=100)),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_passagens', to='Usuario.usuario')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passagens', to='Usuario.viagem')),
            ],
        ),
    ]
