# Generated by Django 6.0.6 on 2026-06-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_de_usuario',
            field=models.CharField(choices=[('cliente', 'Passageiro'), ('guiche', 'Guichê / Operador'), ('administrador', 'Administrador')], max_length=50),
        ),
    ]
