# Generated by Django 6.0.6 on 2026-06-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_remove_viagem_administrador_remove_viagem_rota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passagem',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Preço (R$)'),
            preserve_default=False,
        ),
    ]
